// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LateralMenuController from "./lateral_menu_controller"
application.register("lateral-menu", LateralMenuController)

import MapController from "./map_controller"
application.register("map", MapController)

import MapHomeController from "./map_home_controller"
application.register("map-home", MapHomeController)

import SuggestionsSearchController from "./suggestions_search_controller"
application.register("suggestions-search", SuggestionsSearchController)
